config/routes.rb
Rails.application.routes.draw do
  resources :apps
  resources :posts
  devise_for :users
	root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/app.rb
class App < ApplicationRecord
  belongs_to :post
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

   def getTitle 
   		return self.title
   end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   def username 
   		return self.email.split('@')[0].capitalize
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
	include ActionController::MimeResponds
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  include ActionController::RequestForgeryProtection
  protect_from_forgery with: :exception, unless: -> { request.format.json? }
  before_action :set_app, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
  end

  # GET /apps/new
  def new
    @app = App.new
  end

  # GET /apps/1/edit
  def edit
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(app_params)

    respond_to do |format|
      if @app.save
        format.html { redirect_to @app, notice: 'App was successfully created.' }
        format.json { render :show, status: :created, location: @app }
      else
        format.html { render :new }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apps/1
  # PATCH/PUT /apps/1.json
  def update
    respond_to do |format|
      if @app.update(app_params)
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { render :show, status: :ok, location: @app }
      else
        format.html { render :edit }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app.destroy
    respond_to do |format|
      format.html { redirect_to apps_url, notice: 'App was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app
      @app = App.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_params
      params.require(:app).permit(:Job, :Seen, :post_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ActionController::RequestForgeryProtection
  protect_from_forgery with: :exception, unless: -> { request.format.json? }
  
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!,except: [:show, :index]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/apps/_form.html.erb
<%= form_with(model: app, local: true) do |form| %>
  <% if app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Phone %>
    <%= form.text_field :Job %>
  </div>

  <div class="field" style="display: none">
    <%= form.label :Seen %>
    <%= form.check_box :Seen %>
  </div>

  <div class="field" style="display: none">
    <%= form.label :post_id %>
    <%= form.text_field :post_id ,:value => params[:post_id] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing App</h1>

<%= render 'form', app: @app %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<h1>Job Applications</h1>

<table>
  <thead>
    <tr>
      <th>Job</th>
      <th>Seen</th>
      <th>Phone Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= app.post.getTitle %></td>
        <td><%= app.Seen %></td>
        <td><%= app.Job %></td>
        <td><%= link_to 'Show', app %></td>
        <% if current_user && current_user.admin %>
          <td><%= link_to 'Edit', edit_app_path(app) %></td>
          <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/apps/new.html.erb
<h1>New App</h1>

<%= render 'form', app: @app %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p>
  <strong>Job:</strong>
  <%= @app.post.getTitle %>
</p>
<p>
  <strong>Mobile Number:</strong>
  <%= @app.Job %>
</p>

<p>
  <strong>Seen:</strong>
  <%= @app.Seen %>
</p>


<%= link_to 'Back', apps_path %>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Shoaibi - Task for ZenHR</h1>



<ul>
	<% if user_signed_in? %>
		<li>
			Hello <%= current_user.username %>
		</li>
		<% if current_user && current_user.admin %>
			<li>It's Admin User</li>
		<% end %>
		<li>
			<%= link_to "Sign Out" , destroy_user_session_path,method: :delete %>
		</li>
	<% else %>
		<li>
			<%= link_to "Sign in" , new_user_session_path %>
		</li>
		<li>
			<%= link_to "Sign up" , new_user_registration_path %>
		</li>
	<% end %>
	
	<%= link_to 'Jobs List',posts_path %> | <%= link_to 'Applications List',apps_path %>
</ul>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= link_to 'Show', post %></td>
        <% if current_user && current_user.admin %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user && current_user.admin %>
<%= link_to 'New Post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New Job</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.username %>
</p>
<% if current_user && current_user.admin %>
	<%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %> | <%= link_to 'Apply', new_app_path({:post_id => @post.id}) %>